name:                tinfoiltiger
version:             "0.0.59.1"
github:              "ryangerardwilson/tinfoiltiger"
license:             MIT
author:              "Ryan Gerard Wilson"
maintainer:          "ryangerardwilson@gmail.com"
copyright:           "2025 Ryan Gerard Wilson"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ryangerardwilson/tinfoiltiger#readme>

# Global dependencies applied to all components
dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - file-embed
  - directory
  - process
  - filepath
  - unix
  - raw-strings-qq

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: lib
  dependencies:
    - time
    - http-client
    - http-conduit
    - containers

executables:
  tinfoiltiger:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tinfoiltiger
      - time

tests:
  tinfoiltiger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tinfoiltiger

