name:                YourApp
version:             0.1.0.0
github:              "githubuser/YourApp"
license:             MIT
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"
x-tinfoiltiger:      "QuickStartUp/0.0.53.1"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/YourApp#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: lib
  dependencies:
    - text
    - template-haskell
    - bytestring
    - file-embed
    - regex-tdfa
    - filepath
    - containers
    - hedis
    - scotty
    - http-types
    - uuid
    - transformers
    - wai-middleware-static
    - directory

executables:
  YourApp-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YourApp
      - template-haskell
      - containers
      - scotty
      - file-embed
      - bytestring
      - http-types
      - text
      - wai-middleware-static
      - directory
      - filepath
      - hedis
      - transformers

tests:
  YourApp-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YourApp

